version: "3.8"

services:
  xhgui:
    image: edyan/xhgui:${DOCKER_XHGUI_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_xhgui
    hostname: ${COMPOSE_PROJECT_NAME}_xhgui
    networks: [stakkr]
    mem_limit: ${DOCKER_XHGUI_RAM}
    environment:
      FPM_UID: ${DOCKER_UID}
      FPM_GID: ${DOCKER_GID}
    labels:
      traefik.enable: "true"
      traefik.http.services.xhgui.loadbalancer.server.port: 80
      traefik.http.routers.xhgui.tls: "true"
      traefik.http.routers.xhgui.rule: "Host(`xhgui.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}`)"
  php:
    volumes_from: [xhgui]
