version: '2.2'

services:
    xhgui:
        image: edyan/xhgui:${DOCKER_XHGUI_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_xhgui
        hostname: ${COMPOSE_PROJECT_NAME}_xhgui
        networks: [stakkr]
        mem_limit: ${DOCKER_XHGUI_RAM}
        environment:
            FPM_UID: ${DOCKER_UID}
            FPM_GID: ${DOCKER_GID}
        labels:
            - traefik.frontend.rule=Host:xhgui.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
    php:
        volumes_from: [xhgui]
        # Local configuration to override the one which connects in local
        volumes:
            - ${COMPOSE_BASE_DIR}/conf/xhgui-override/config.php:/usr/local/src/xhgui/config/config.php
